/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as StructuredRouteImport } from './routes/structured'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as SubjectRouteImport } from './routes/$subject'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as SubjectIndexRouteImport } from './routes/$subject.index'
import { Route as PracticeModeRouteImport } from './routes/practice.$mode'
import { Route as SubjectTopicRouteImport } from './routes/$subject.$topic'
import { Route as PracticeModeIndexRouteImport } from './routes/practice.$mode.index'
import { Route as SubjectTopicIndexRouteImport } from './routes/$subject.$topic.index'
import { Route as PracticeModeSubjectRouteImport } from './routes/practice.$mode.$subject'
import { Route as ExamStructuredSubjectRouteImport } from './routes/exam.structured.$subject'
import { Route as ExamShortSubjectRouteImport } from './routes/exam.short.$subject'
import { Route as SubjectTopicResultsRouteImport } from './routes/$subject.$topic.results'
import { Route as SubjectTopicPracticeRouteImport } from './routes/$subject.$topic.practice'
import { Route as LearnSubjectTopicSlugRouteImport } from './routes/learn.$subject.$topic.$slug'

const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuredRoute = StructuredRouteImport.update({
  id: '/structured',
  path: '/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectRoute = SubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const SubjectIndexRoute = SubjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectRoute,
} as any)
const PracticeModeRoute = PracticeModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => PracticeRoute,
} as any)
const SubjectTopicRoute = SubjectTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => SubjectRoute,
} as any)
const PracticeModeIndexRoute = PracticeModeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeModeRoute,
} as any)
const SubjectTopicIndexRoute = SubjectTopicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectTopicRoute,
} as any)
const PracticeModeSubjectRoute = PracticeModeSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => PracticeModeRoute,
} as any)
const ExamStructuredSubjectRoute = ExamStructuredSubjectRouteImport.update({
  id: '/structured/$subject',
  path: '/structured/$subject',
  getParentRoute: () => ExamRoute,
} as any)
const ExamShortSubjectRoute = ExamShortSubjectRouteImport.update({
  id: '/short/$subject',
  path: '/short/$subject',
  getParentRoute: () => ExamRoute,
} as any)
const SubjectTopicResultsRoute = SubjectTopicResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SubjectTopicRoute,
} as any)
const SubjectTopicPracticeRoute = SubjectTopicPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => SubjectTopicRoute,
} as any)
const LearnSubjectTopicSlugRoute = LearnSubjectTopicSlugRouteImport.update({
  id: '/learn/$subject/$topic/$slug',
  path: '/learn/$subject/$topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/exam': typeof ExamRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/structured': typeof StructuredRoute
  '/suggest': typeof SuggestRoute
  '/$subject/$topic': typeof SubjectTopicRouteWithChildren
  '/practice/$mode': typeof PracticeModeRouteWithChildren
  '/$subject/': typeof SubjectIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/$subject/$topic/practice': typeof SubjectTopicPracticeRoute
  '/$subject/$topic/results': typeof SubjectTopicResultsRoute
  '/exam/short/$subject': typeof ExamShortSubjectRoute
  '/exam/structured/$subject': typeof ExamStructuredSubjectRoute
  '/practice/$mode/$subject': typeof PracticeModeSubjectRoute
  '/$subject/$topic/': typeof SubjectTopicIndexRoute
  '/practice/$mode/': typeof PracticeModeIndexRoute
  '/learn/$subject/$topic/$slug': typeof LearnSubjectTopicSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam': typeof ExamRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/structured': typeof StructuredRoute
  '/suggest': typeof SuggestRoute
  '/$subject': typeof SubjectIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/$subject/$topic/practice': typeof SubjectTopicPracticeRoute
  '/$subject/$topic/results': typeof SubjectTopicResultsRoute
  '/exam/short/$subject': typeof ExamShortSubjectRoute
  '/exam/structured/$subject': typeof ExamStructuredSubjectRoute
  '/practice/$mode/$subject': typeof PracticeModeSubjectRoute
  '/$subject/$topic': typeof SubjectTopicIndexRoute
  '/practice/$mode': typeof PracticeModeIndexRoute
  '/learn/$subject/$topic/$slug': typeof LearnSubjectTopicSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/exam': typeof ExamRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/structured': typeof StructuredRoute
  '/suggest': typeof SuggestRoute
  '/$subject/$topic': typeof SubjectTopicRouteWithChildren
  '/practice/$mode': typeof PracticeModeRouteWithChildren
  '/$subject/': typeof SubjectIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/$subject/$topic/practice': typeof SubjectTopicPracticeRoute
  '/$subject/$topic/results': typeof SubjectTopicResultsRoute
  '/exam/short/$subject': typeof ExamShortSubjectRoute
  '/exam/structured/$subject': typeof ExamStructuredSubjectRoute
  '/practice/$mode/$subject': typeof PracticeModeSubjectRoute
  '/$subject/$topic/': typeof SubjectTopicIndexRoute
  '/practice/$mode/': typeof PracticeModeIndexRoute
  '/learn/$subject/$topic/$slug': typeof LearnSubjectTopicSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$subject'
    | '/exam'
    | '/practice'
    | '/reviews'
    | '/sitemap.xml'
    | '/structured'
    | '/suggest'
    | '/$subject/$topic'
    | '/practice/$mode'
    | '/$subject/'
    | '/practice/'
    | '/$subject/$topic/practice'
    | '/$subject/$topic/results'
    | '/exam/short/$subject'
    | '/exam/structured/$subject'
    | '/practice/$mode/$subject'
    | '/$subject/$topic/'
    | '/practice/$mode/'
    | '/learn/$subject/$topic/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam'
    | '/reviews'
    | '/sitemap.xml'
    | '/structured'
    | '/suggest'
    | '/$subject'
    | '/practice'
    | '/$subject/$topic/practice'
    | '/$subject/$topic/results'
    | '/exam/short/$subject'
    | '/exam/structured/$subject'
    | '/practice/$mode/$subject'
    | '/$subject/$topic'
    | '/practice/$mode'
    | '/learn/$subject/$topic/$slug'
  id:
    | '__root__'
    | '/'
    | '/$subject'
    | '/exam'
    | '/practice'
    | '/reviews'
    | '/sitemap.xml'
    | '/structured'
    | '/suggest'
    | '/$subject/$topic'
    | '/practice/$mode'
    | '/$subject/'
    | '/practice/'
    | '/$subject/$topic/practice'
    | '/$subject/$topic/results'
    | '/exam/short/$subject'
    | '/exam/structured/$subject'
    | '/practice/$mode/$subject'
    | '/$subject/$topic/'
    | '/practice/$mode/'
    | '/learn/$subject/$topic/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubjectRoute: typeof SubjectRouteWithChildren
  ExamRoute: typeof ExamRouteWithChildren
  PracticeRoute: typeof PracticeRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StructuredRoute: typeof StructuredRoute
  SuggestRoute: typeof SuggestRoute
  LearnSubjectTopicSlugRoute: typeof LearnSubjectTopicSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structured': {
      id: '/structured'
      path: '/structured'
      fullPath: '/structured'
      preLoaderRoute: typeof StructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject': {
      id: '/$subject'
      path: '/$subject'
      fullPath: '/$subject'
      preLoaderRoute: typeof SubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/$subject/': {
      id: '/$subject/'
      path: '/'
      fullPath: '/$subject/'
      preLoaderRoute: typeof SubjectIndexRouteImport
      parentRoute: typeof SubjectRoute
    }
    '/practice/$mode': {
      id: '/practice/$mode'
      path: '/$mode'
      fullPath: '/practice/$mode'
      preLoaderRoute: typeof PracticeModeRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/$subject/$topic': {
      id: '/$subject/$topic'
      path: '/$topic'
      fullPath: '/$subject/$topic'
      preLoaderRoute: typeof SubjectTopicRouteImport
      parentRoute: typeof SubjectRoute
    }
    '/practice/$mode/': {
      id: '/practice/$mode/'
      path: '/'
      fullPath: '/practice/$mode/'
      preLoaderRoute: typeof PracticeModeIndexRouteImport
      parentRoute: typeof PracticeModeRoute
    }
    '/$subject/$topic/': {
      id: '/$subject/$topic/'
      path: '/'
      fullPath: '/$subject/$topic/'
      preLoaderRoute: typeof SubjectTopicIndexRouteImport
      parentRoute: typeof SubjectTopicRoute
    }
    '/practice/$mode/$subject': {
      id: '/practice/$mode/$subject'
      path: '/$subject'
      fullPath: '/practice/$mode/$subject'
      preLoaderRoute: typeof PracticeModeSubjectRouteImport
      parentRoute: typeof PracticeModeRoute
    }
    '/exam/structured/$subject': {
      id: '/exam/structured/$subject'
      path: '/structured/$subject'
      fullPath: '/exam/structured/$subject'
      preLoaderRoute: typeof ExamStructuredSubjectRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/short/$subject': {
      id: '/exam/short/$subject'
      path: '/short/$subject'
      fullPath: '/exam/short/$subject'
      preLoaderRoute: typeof ExamShortSubjectRouteImport
      parentRoute: typeof ExamRoute
    }
    '/$subject/$topic/results': {
      id: '/$subject/$topic/results'
      path: '/results'
      fullPath: '/$subject/$topic/results'
      preLoaderRoute: typeof SubjectTopicResultsRouteImport
      parentRoute: typeof SubjectTopicRoute
    }
    '/$subject/$topic/practice': {
      id: '/$subject/$topic/practice'
      path: '/practice'
      fullPath: '/$subject/$topic/practice'
      preLoaderRoute: typeof SubjectTopicPracticeRouteImport
      parentRoute: typeof SubjectTopicRoute
    }
    '/learn/$subject/$topic/$slug': {
      id: '/learn/$subject/$topic/$slug'
      path: '/learn/$subject/$topic/$slug'
      fullPath: '/learn/$subject/$topic/$slug'
      preLoaderRoute: typeof LearnSubjectTopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SubjectTopicRouteChildren {
  SubjectTopicPracticeRoute: typeof SubjectTopicPracticeRoute
  SubjectTopicResultsRoute: typeof SubjectTopicResultsRoute
  SubjectTopicIndexRoute: typeof SubjectTopicIndexRoute
}

const SubjectTopicRouteChildren: SubjectTopicRouteChildren = {
  SubjectTopicPracticeRoute: SubjectTopicPracticeRoute,
  SubjectTopicResultsRoute: SubjectTopicResultsRoute,
  SubjectTopicIndexRoute: SubjectTopicIndexRoute,
}

const SubjectTopicRouteWithChildren = SubjectTopicRoute._addFileChildren(
  SubjectTopicRouteChildren,
)

interface SubjectRouteChildren {
  SubjectTopicRoute: typeof SubjectTopicRouteWithChildren
  SubjectIndexRoute: typeof SubjectIndexRoute
}

const SubjectRouteChildren: SubjectRouteChildren = {
  SubjectTopicRoute: SubjectTopicRouteWithChildren,
  SubjectIndexRoute: SubjectIndexRoute,
}

const SubjectRouteWithChildren =
  SubjectRoute._addFileChildren(SubjectRouteChildren)

interface ExamRouteChildren {
  ExamShortSubjectRoute: typeof ExamShortSubjectRoute
  ExamStructuredSubjectRoute: typeof ExamStructuredSubjectRoute
}

const ExamRouteChildren: ExamRouteChildren = {
  ExamShortSubjectRoute: ExamShortSubjectRoute,
  ExamStructuredSubjectRoute: ExamStructuredSubjectRoute,
}

const ExamRouteWithChildren = ExamRoute._addFileChildren(ExamRouteChildren)

interface PracticeModeRouteChildren {
  PracticeModeSubjectRoute: typeof PracticeModeSubjectRoute
  PracticeModeIndexRoute: typeof PracticeModeIndexRoute
}

const PracticeModeRouteChildren: PracticeModeRouteChildren = {
  PracticeModeSubjectRoute: PracticeModeSubjectRoute,
  PracticeModeIndexRoute: PracticeModeIndexRoute,
}

const PracticeModeRouteWithChildren = PracticeModeRoute._addFileChildren(
  PracticeModeRouteChildren,
)

interface PracticeRouteChildren {
  PracticeModeRoute: typeof PracticeModeRouteWithChildren
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeModeRoute: PracticeModeRouteWithChildren,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubjectRoute: SubjectRouteWithChildren,
  ExamRoute: ExamRouteWithChildren,
  PracticeRoute: PracticeRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StructuredRoute: StructuredRoute,
  SuggestRoute: SuggestRoute,
  LearnSubjectTopicSlugRoute: LearnSubjectTopicSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
