/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectRouteImport } from './routes/$subject'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectTopicRouteImport } from './routes/$subject.$topic'
import { Route as SubjectTopicResultsRouteImport } from './routes/$subject.$topic.results'
import { Route as SubjectTopicPracticeRouteImport } from './routes/$subject.$topic.practice'

const SubjectRoute = SubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectTopicRoute = SubjectTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => SubjectRoute,
} as any)
const SubjectTopicResultsRoute = SubjectTopicResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SubjectTopicRoute,
} as any)
const SubjectTopicPracticeRoute = SubjectTopicPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => SubjectTopicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/$subject/$topic': typeof SubjectTopicRouteWithChildren
  '/$subject/$topic/practice': typeof SubjectTopicPracticeRoute
  '/$subject/$topic/results': typeof SubjectTopicResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/$subject/$topic': typeof SubjectTopicRouteWithChildren
  '/$subject/$topic/practice': typeof SubjectTopicPracticeRoute
  '/$subject/$topic/results': typeof SubjectTopicResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/$subject/$topic': typeof SubjectTopicRouteWithChildren
  '/$subject/$topic/practice': typeof SubjectTopicPracticeRoute
  '/$subject/$topic/results': typeof SubjectTopicResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$subject'
    | '/$subject/$topic'
    | '/$subject/$topic/practice'
    | '/$subject/$topic/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$subject'
    | '/$subject/$topic'
    | '/$subject/$topic/practice'
    | '/$subject/$topic/results'
  id:
    | '__root__'
    | '/'
    | '/$subject'
    | '/$subject/$topic'
    | '/$subject/$topic/practice'
    | '/$subject/$topic/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubjectRoute: typeof SubjectRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$subject': {
      id: '/$subject'
      path: '/$subject'
      fullPath: '/$subject'
      preLoaderRoute: typeof SubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject/$topic': {
      id: '/$subject/$topic'
      path: '/$topic'
      fullPath: '/$subject/$topic'
      preLoaderRoute: typeof SubjectTopicRouteImport
      parentRoute: typeof SubjectRoute
    }
    '/$subject/$topic/results': {
      id: '/$subject/$topic/results'
      path: '/results'
      fullPath: '/$subject/$topic/results'
      preLoaderRoute: typeof SubjectTopicResultsRouteImport
      parentRoute: typeof SubjectTopicRoute
    }
    '/$subject/$topic/practice': {
      id: '/$subject/$topic/practice'
      path: '/practice'
      fullPath: '/$subject/$topic/practice'
      preLoaderRoute: typeof SubjectTopicPracticeRouteImport
      parentRoute: typeof SubjectTopicRoute
    }
  }
}

interface SubjectTopicRouteChildren {
  SubjectTopicPracticeRoute: typeof SubjectTopicPracticeRoute
  SubjectTopicResultsRoute: typeof SubjectTopicResultsRoute
}

const SubjectTopicRouteChildren: SubjectTopicRouteChildren = {
  SubjectTopicPracticeRoute: SubjectTopicPracticeRoute,
  SubjectTopicResultsRoute: SubjectTopicResultsRoute,
}

const SubjectTopicRouteWithChildren = SubjectTopicRoute._addFileChildren(
  SubjectTopicRouteChildren,
)

interface SubjectRouteChildren {
  SubjectTopicRoute: typeof SubjectTopicRouteWithChildren
}

const SubjectRouteChildren: SubjectRouteChildren = {
  SubjectTopicRoute: SubjectTopicRouteWithChildren,
}

const SubjectRouteWithChildren =
  SubjectRoute._addFileChildren(SubjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubjectRoute: SubjectRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
