REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_class_teacher(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_class_member(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.shares_class(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.assignment_class(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, public, authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_class_teacher(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_class_member(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.shares_class(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.assignment_class(uuid) TO authenticated, service_role;